export const ADD_ACTION_IN_ARRAY = 'ADD_ACTION_IN_ARRAY';
export const ADD_ACTION_CONST_TYPE = 'ADD_ACTION_CONST_TYPE';
export const REMOVE_ACTION = 'REMOVE_ACTION';
export const CHECK_ACTION = 'CHECK_ACTION';
export const ADD_URGENCY_ELEMENTS = 'ADD_URGENCY_ELEMENTS';
export const CHANGE_ACTION = 'CHANGE_ACTION';
export const RESET_ARRAY_DATA_TO_SELECT = 'RESET_ARRAY_DATA_TO_SELECT';
export const EDIT_LOADING = 'EDIT_LOADING';